[theme]
# Force light mode
base = "light"
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
# Additional server settings
headless = true
enableCORS = false
enableXsrfProtection = false
